#!/usr/bin/env bash
set -euo pipefail

# upscale_video_auto.sh
# Uses config generated by setup_realesrgan_auto.sh.
# Supports:
# - PyTorch Real-ESRGAN
# - Real-ESRGAN NCNN Vulkan
# - Real-CUGAN NCNN Vulkan
#
# Key fixes in this version:
# - CLI options override config values.
# - --backend auto is resolved at runtime.
# - Output frame pattern is auto-detected (_out.png vs .png).
# - Split is range-based instead of alternating frames.
# - Cleanup modes are explicit and guarded.

CONFIG_FILE="$HOME/realesrgan/realesrgan_auto.conf"

CLI_INPUT=""
CLI_OUTPUT=""
CLI_WORKDIR=""
CLI_BACKEND=""
CLI_GPUS=""
CLI_GPU_COUNT=""
CLI_CONTENT=""
CLI_MODEL=""
CLI_OUTSCALE=""
CLI_TILE=""
CLI_FRAME_FORMAT=""
CLI_CONTAINER=""
CLI_CQ=""

CLEAN=0
CLEAN_ALL=0
DELETE_TEMP=0
RESUME=0
FORCE=0

usage() {
cat << EOF
Usage:
  ./upscale_video_auto.sh --input video.mkv [options]

Required:
  -i, --input FILE

Options:
  -o, --output FILE
  --config FILE
  --workdir DIR
  --backend auto|pytorch|ncnn|realcugan
  --gpus 0,1
  --gpu-count N
  --interactive
  --content anime|old-anime|cartoon|live|low-quality|restore
  --model auto|realesr-animevideov3|RealESRGAN_x4plus_anime_6B|RealESRGAN_x4plus
  --outscale N
  --tile N
  --frame-format png|jpg
  --container mkv|mp4
  --cq N
  --clean          Delete previous output/temp folders for this run
  --clean-all      Delete all extracted frames/audio/temp files first
  --delete-temp    Delete temporary files after successful output
  --resume         Keep existing files and continue
  --force          Skip cleanup prompts
  -h, --help

Examples:
  ./upscale_video_auto.sh -i input.mkv --clean
  ./upscale_video_auto.sh -i input.mkv --gpus 0,1 --model realesr-animevideov3
  ./upscale_video_auto.sh -i input.mkv --backend realcugan --outscale 2
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -i|--input) CLI_INPUT="${2:-}"; shift 2 ;;
    -o|--output) CLI_OUTPUT="${2:-}"; shift 2 ;;
    --config) CONFIG_FILE="${2:-}"; shift 2 ;;
    --workdir) CLI_WORKDIR="${2:-}"; shift 2 ;;
    --backend) CLI_BACKEND="${2:-}"; shift 2 ;;
    --gpus) CLI_GPUS="${2:-}"; shift 2 ;;
    --gpu-count) CLI_GPU_COUNT="${2:-}"; shift 2 ;;
    --content) CLI_CONTENT="${2:-}"; shift 2 ;;
    --model) CLI_MODEL="${2:-}"; shift 2 ;;
    --outscale) CLI_OUTSCALE="${2:-}"; shift 2 ;;
    --tile) CLI_TILE="${2:-}"; shift 2 ;;
    --frame-format) CLI_FRAME_FORMAT="${2:-}"; shift 2 ;;
    --container) CLI_CONTAINER="${2:-}"; shift 2 ;;
    --cq) CLI_CQ="${2:-}"; shift 2 ;;
    --clean) CLEAN=1; shift ;;
    --clean-all) CLEAN_ALL=1; shift ;;
    --delete-temp) DELETE_TEMP=1; shift ;;
    --resume) RESUME=1; shift ;;
    --force) FORCE=1; shift ;;
    --interactive) INTERACTIVE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

# Defaults before config
INSTALL_DIR="$HOME/realesrgan"
BACKEND="auto"
SELECTED_GPUS=""
MODEL="realesr-animevideov3"
OUTSCALE="2"
TILE="1200"
CONTAINER="mkv"
CQ="18"
FRAME_FORMAT="png"
NCNN_BIN=""
REALCUGAN_BIN=""
WORKDIR="$HOME/video_upscale"
CONTENT="anime"

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
fi

# CLI overrides config
INPUT="${CLI_INPUT}"
OUTPUT="${CLI_OUTPUT}"
[[ -n "$CLI_WORKDIR" ]] && WORKDIR="$CLI_WORKDIR"
[[ -n "$CLI_BACKEND" ]] && BACKEND="$CLI_BACKEND"
[[ -n "$CLI_GPUS" ]] && SELECTED_GPUS="$CLI_GPUS"
[[ -n "$CLI_CONTENT" ]] && CONTENT="$CLI_CONTENT"
[[ -n "$CLI_MODEL" ]] && MODEL="$CLI_MODEL"
[[ -n "$CLI_OUTSCALE" ]] && OUTSCALE="$CLI_OUTSCALE"
[[ -n "$CLI_TILE" ]] && TILE="$CLI_TILE"
[[ -n "$CLI_FRAME_FORMAT" ]] && FRAME_FORMAT="$CLI_FRAME_FORMAT"
[[ -n "$CLI_CONTAINER" ]] && CONTAINER="$CLI_CONTAINER"
[[ -n "$CLI_CQ" ]] && CQ="$CLI_CQ"

[[ -n "$INPUT" ]] || { echo "ERROR: --input is required"; usage; exit 1; }
[[ -f "$INPUT" ]] || { echo "ERROR: input not found: $INPUT"; exit 1; }

resolve_backend_auto() {
  if [[ "$BACKEND" != "auto" ]]; then
    return
  fi

  if [[ -d "$INSTALL_DIR/Real-ESRGAN" ]]; then
    BACKEND="pytorch"
  elif [[ -n "$NCNN_BIN" || -d "$INSTALL_DIR/ncnn" ]]; then
    BACKEND="ncnn"
  elif [[ -n "$REALCUGAN_BIN" || -d "$INSTALL_DIR/realcugan" ]]; then
    BACKEND="realcugan"
  else
    echo "ERROR: Could not resolve backend=auto. Run setup first."
    exit 1
  fi
}

resolve_backend_auto


content_wizard() {
  [[ "$INTERACTIVE" -eq 1 ]] || return 0

  echo
  echo "Select content type:"
  echo "  1) Anime / animation video"
  echo "  2) Old anime / softer source"
  echo "  3) Cartoon / western animation"
  echo "  4) Live action / real video"
  echo "  5) Low-quality / noisy source"
  echo "  6) Restore only / avoid heavy upscale"
  read -r -p "Choose [1-6] default 1: " choice

  case "${choice:-1}" in
    1) CONTENT="anime" ;;
    2) CONTENT="old-anime" ;;
    3) CONTENT="cartoon" ;;
    4) CONTENT="live" ;;
    5) CONTENT="low-quality" ;;
    6) CONTENT="restore" ;;
    *) CONTENT="anime" ;;
  esac
}

apply_content_defaults() {
  if [[ "$MODEL" == "auto" ]]; then
    case "$CONTENT" in
      anime|old-anime|cartoon)
        MODEL="realesr-animevideov3"
        ;;
      live)
        MODEL="RealESRGAN_x4plus"
        ;;
      low-quality|restore)
        MODEL="realesr-animevideov3"
        ;;
      *)
        MODEL="realesr-animevideov3"
        ;;
    esac
  fi

  if [[ -z "$OUTSCALE" ]]; then
    case "$CONTENT" in
      low-quality|restore) OUTSCALE=1 ;;
      *) OUTSCALE=2 ;;
    esac
  fi

  if [[ "$BACKEND" == "realcugan" ]]; then
    MODEL="realcugan"
    [[ -z "$OUTSCALE" || "$OUTSCALE" -lt 2 ]] && OUTSCALE=2
  fi
}

content_wizard
apply_content_defaults

if [[ -z "$OUTPUT" ]]; then
  stem="$(basename "$INPUT")"
  stem="${stem%.*}"
  OUTPUT="$WORKDIR/${stem}_upscaled.${CONTAINER}"
fi

FPS="$(ffprobe -v 0 -select_streams v:0 -show_entries stream=r_frame_rate -of default=noprint_wrappers=1:nokey=1 "$INPUT")"
[[ -n "$FPS" ]] || { echo "ERROR: Could not detect frame rate."; exit 1; }

echo "Input:        $INPUT"
echo "Output:       $OUTPUT"
echo "FPS:          $FPS"
echo "Backend:      $BACKEND"
echo "Model:        $MODEL"
echo "Outscale:     $OUTSCALE"
echo "Tile:         $TILE"
echo "Frame format: $FRAME_FORMAT"
echo "Workdir:      $WORKDIR"

mkdir -p "$WORKDIR"/{input_frames,output_frames_final,logs}
mkdir -p "$(dirname "$OUTPUT")"

if [[ "$RESUME" -eq 1 ]]; then
  CLEAN=0
  CLEAN_ALL=0
fi

confirm_delete() {
  [[ "$FORCE" -eq 1 ]] && return 0
  echo "Cleanup requested in: $WORKDIR"
  read -r -p "Continue deleting temp files? [y/N]: " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Cancelled."; exit 0; }
}

if [[ "$CLEAN_ALL" -eq 1 ]]; then
  confirm_delete
  rm -rf "$WORKDIR"/input_frames/*
  rm -rf "$WORKDIR"/input_frames_part*
  rm -rf "$WORKDIR"/output_frames_part*
  rm -rf "$WORKDIR"/output_frames_final/*
  rm -f "$WORKDIR"/original_audio.*
  rm -f "$WORKDIR"/upscaled_video.*
elif [[ "$CLEAN" -eq 1 ]]; then
  confirm_delete
  rm -rf "$WORKDIR"/input_frames_part*
  rm -rf "$WORKDIR"/output_frames_part*
  rm -rf "$WORKDIR"/output_frames_final/*
  rm -f "$WORKDIR"/upscaled_video.*
fi

echo "Extracting audio..."
if [[ "$RESUME" -eq 0 || ! -f "$WORKDIR/original_audio.mka" ]]; then
  ffmpeg -y -i "$INPUT" -vn -acodec copy "$WORKDIR/original_audio.mka" || true
fi

echo "Extracting frames..."
if [[ "$RESUME" -eq 0 || -z "$(find "$WORKDIR/input_frames" -type f -name "*.${FRAME_FORMAT}" 2>/dev/null | head -1)" ]]; then
  ffmpeg -y -i "$INPUT" "$WORKDIR/input_frames/%08d.${FRAME_FORMAT}"
fi

prepare_gpu_array() {
  local gpus="$SELECTED_GPUS"
  if [[ -z "$gpus" && "$BACKEND" == "pytorch" ]]; then
    gpus="0"
  fi
  if [[ -n "$CLI_GPU_COUNT" && -n "$gpus" ]]; then
    gpus="$(echo "$gpus" | tr ',' '\n' | head -n "$CLI_GPU_COUNT" | paste -sd, -)"
  fi

  IFS=',' read -r -a GPU_ARRAY <<< "$gpus"
  if [[ "$BACKEND" == "pytorch" && "${#GPU_ARRAY[@]}" -eq 0 ]]; then
    GPU_ARRAY=("0")
  fi
}

split_frames_by_range() {
  echo "Splitting frames by ranges..."
  local parts="${#GPU_ARRAY[@]}"
  [[ "$parts" -gt 0 ]] || parts=1

  mapfile -t FRAMES < <(find "$WORKDIR/input_frames" -maxdepth 1 -type f -name "*.${FRAME_FORMAT}" | sort)
  local total="${#FRAMES[@]}"
  [[ "$total" -gt 0 ]] || { echo "ERROR: no frames found"; exit 1; }

  for ((p=0; p<parts; p++)); do
    rm -rf "$WORKDIR/input_frames_part$p" "$WORKDIR/output_frames_part$p"
    mkdir -p "$WORKDIR/input_frames_part$p" "$WORKDIR/output_frames_part$p"
  done

  local chunk=$(( (total + parts - 1) / parts ))
  for ((p=0; p<parts; p++)); do
    local start=$(( p * chunk ))
    local end=$(( start + chunk ))
    (( end > total )) && end="$total"

    for ((i=start; i<end; i++)); do
      cp "${FRAMES[$i]}" "$WORKDIR/input_frames_part$p/"
    done

    echo "Part $p frames: $(( end - start ))"
  done
}

prepare_gpu_array
echo "Selected GPUs: ${GPU_ARRAY[*]:-vulkan/default}"

if [[ "$BACKEND" == "pytorch" ]]; then
  split_frames_by_range

  cd "$INSTALL_DIR/Real-ESRGAN"
  source venv/bin/activate

  PIDS=()
  part=0
  for gpu in "${GPU_ARRAY[@]}"; do
    echo "Starting PyTorch RealESRGAN on GPU $gpu, part $part"
    CUDA_VISIBLE_DEVICES="$gpu" python inference_realesrgan.py \
      -n "$MODEL" \
      -i "$WORKDIR/input_frames_part$part" \
      -o "$WORKDIR/output_frames_part$part" \
      --outscale "$OUTSCALE" \
      --tile "$TILE" &
    PIDS+=("$!")
    part=$((part+1))
  done
  for pid in "${PIDS[@]}"; do wait "$pid"; done

elif [[ "$BACKEND" == "ncnn" ]]; then
  mkdir -p "$WORKDIR/output_frames_part0"
  if [[ -z "$NCNN_BIN" ]]; then
    NCNN_BIN="$(find "$INSTALL_DIR/ncnn" -type f -name realesrgan-ncnn-vulkan | head -1)"
  fi
  [[ -x "$NCNN_BIN" ]] || { echo "ERROR: NCNN binary not found. Run setup."; exit 1; }
  "$NCNN_BIN" -i "$WORKDIR/input_frames" -o "$WORKDIR/output_frames_part0" -n "$MODEL" -s "$OUTSCALE"

elif [[ "$BACKEND" == "realcugan" ]]; then
  mkdir -p "$WORKDIR/output_frames_part0"
  if [[ -z "$REALCUGAN_BIN" ]]; then
    REALCUGAN_BIN="$(find "$INSTALL_DIR/realcugan" -type f -name realcugan-ncnn-vulkan | head -1)"
  fi
  [[ -x "$REALCUGAN_BIN" ]] || { echo "ERROR: Real-CUGAN binary not found. Run setup."; exit 1; }
  "$REALCUGAN_BIN" -i "$WORKDIR/input_frames" -o "$WORKDIR/output_frames_part0" -s "$OUTSCALE" -n -1

else
  echo "ERROR: Unknown backend: $BACKEND"
  exit 1
fi

echo "Merging output frames..."
rm -rf "$WORKDIR/output_frames_final"/*
find "$WORKDIR" -maxdepth 1 -type d -name "output_frames_part*" | sort | while read -r d; do
  cp "$d"/* "$WORKDIR/output_frames_final/" 2>/dev/null || true
done

# Detect output pattern. PyTorch usually creates %08d_out.png.
# NCNN/Real-CUGAN commonly keep the original %08d.png name.
INPUT_PATTERN=""
if ls "$WORKDIR"/output_frames_final/*_out."$FRAME_FORMAT" >/dev/null 2>&1; then
  INPUT_PATTERN="$WORKDIR/output_frames_final/%08d_out.${FRAME_FORMAT}"
elif ls "$WORKDIR"/output_frames_final/*."$FRAME_FORMAT" >/dev/null 2>&1; then
  INPUT_PATTERN="$WORKDIR/output_frames_final/%08d.${FRAME_FORMAT}"
else
  echo "ERROR: No output frames found in $WORKDIR/output_frames_final"
  exit 1
fi

echo "Using frame pattern: $INPUT_PATTERN"

echo "Encoding video..."
upscaled_video="$WORKDIR/upscaled_video.${CONTAINER}"
ffmpeg -y \
  -framerate "$FPS" \
  -i "$INPUT_PATTERN" \
  -c:v hevc_nvenc \
  -preset p7 \
  -profile:v main10 \
  -pix_fmt p010le \
  -rc vbr \
  -cq "$CQ" \
  -b:v 0 \
  "$upscaled_video"

echo "Adding original audio..."
if [[ -f "$WORKDIR/original_audio.mka" ]]; then
  ffmpeg -y \
    -i "$upscaled_video" \
    -i "$WORKDIR/original_audio.mka" \
    -map 0:v:0 \
    -map 1:a? \
    -c:v copy \
    -c:a copy \
    "$OUTPUT"
else
  cp "$upscaled_video" "$OUTPUT"
fi

echo "Final output: $OUTPUT"

if [[ "$DELETE_TEMP" -eq 1 ]]; then
  echo "Deleting temp files after successful output..."
  rm -rf "$WORKDIR"/input_frames "$WORKDIR"/input_frames_part* "$WORKDIR"/output_frames_part* "$WORKDIR"/output_frames_final
  rm -f "$WORKDIR"/original_audio.* "$WORKDIR"/upscaled_video.*
fi
